// This file is @generated by prost-build.
/// Agent registration and identification
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AgentInfo {
    /// UUID v4, generated on first run
    #[prost(string, tag = "1")]
    pub agent_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub hostname: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub os_name: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub kernel_version: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub agent_version: ::prost::alloc::string::String,
    #[prost(uint32, tag = "6")]
    pub cpu_cores: u32,
    #[prost(string, tag = "7")]
    pub cpu_name: ::prost::alloc::string::String,
    /// Optional group for categorization (e.g., "web-servers", "databases")
    #[prost(string, tag = "8")]
    pub agent_group: ::prost::alloc::string::String,
    /// True if agent is running as root (uid 0)
    #[prost(bool, tag = "9")]
    pub is_root: bool,
    /// Number of messages waiting in offline queue
    #[prost(uint32, tag = "10")]
    pub queue_pending_count: u32,
    /// Size of pending queue in bytes
    #[prost(uint64, tag = "11")]
    pub queue_pending_bytes: u64,
}
/// Core metrics snapshot - sent periodically
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MetricsSnapshot {
    #[prost(message, optional, tag = "1")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(string, tag = "2")]
    pub agent_id: ::prost::alloc::string::String,
    /// CPU metrics
    #[prost(double, tag = "10")]
    pub cpu_usage_percent: f64,
    #[prost(double, tag = "11")]
    pub cpu_io_wait_percent: f64,
    /// Memory metrics (in KiB)
    #[prost(uint64, tag = "20")]
    pub memory_used_kib: u64,
    #[prost(uint64, tag = "21")]
    pub memory_available_kib: u64,
    #[prost(uint64, tag = "22")]
    pub memory_total_kib: u64,
    #[prost(uint64, tag = "23")]
    pub swap_free_kib: u64,
    #[prost(uint64, tag = "24")]
    pub swap_total_kib: u64,
    /// Per-disk I/O metrics
    #[prost(message, repeated, tag = "30")]
    pub disks: ::prost::alloc::vec::Vec<DiskMetrics>,
    /// Per-interface network metrics
    #[prost(message, repeated, tag = "40")]
    pub network: ::prost::alloc::vec::Vec<NetworkMetrics>,
    /// PSI pressure (optional, Linux 4.20+)
    #[prost(message, optional, tag = "50")]
    pub pressure: ::core::option::Option<PressureMetrics>,
    /// Queue sync status (messages pending to be sent from offline queue)
    ///
    /// Number of messages waiting in offline queue
    #[prost(uint32, tag = "60")]
    pub queue_pending_count: u32,
    /// Size of pending queue in bytes
    #[prost(uint64, tag = "61")]
    pub queue_pending_bytes: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DiskMetrics {
    #[prost(string, tag = "1")]
    pub device: ::prost::alloc::string::String,
    #[prost(uint64, tag = "2")]
    pub read_ops: u64,
    #[prost(uint64, tag = "3")]
    pub write_ops: u64,
    #[prost(uint64, tag = "4")]
    pub read_time_ms: u64,
    #[prost(uint64, tag = "5")]
    pub write_time_ms: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NetworkMetrics {
    #[prost(string, tag = "1")]
    pub interface_name: ::prost::alloc::string::String,
    #[prost(uint64, tag = "2")]
    pub bytes_received: u64,
    #[prost(uint64, tag = "3")]
    pub bytes_transmitted: u64,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct PressureMetrics {
    #[prost(message, optional, tag = "1")]
    pub cpu: ::core::option::Option<PressureEntry>,
    #[prost(message, optional, tag = "2")]
    pub memory: ::core::option::Option<PressureEntry>,
    #[prost(message, optional, tag = "3")]
    pub io: ::core::option::Option<PressureEntry>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct PressureEntry {
    #[prost(message, optional, tag = "1")]
    pub some: ::core::option::Option<PressureAverages>,
    #[prost(message, optional, tag = "2")]
    pub full: ::core::option::Option<PressureAverages>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct PressureAverages {
    #[prost(double, tag = "1")]
    pub avg10: f64,
    #[prost(double, tag = "2")]
    pub avg60: f64,
    #[prost(double, tag = "3")]
    pub avg300: f64,
    #[prost(uint64, tag = "4")]
    pub total: u64,
}
/// Wrapper for all messages with authentication
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AuthenticatedMessage {
    #[prost(string, tag = "1")]
    pub api_key: ::prost::alloc::string::String,
    #[prost(oneof = "authenticated_message::Payload", tags = "10, 11, 12, 13")]
    pub payload: ::core::option::Option<authenticated_message::Payload>,
}
/// Nested message and enum types in `AuthenticatedMessage`.
pub mod authenticated_message {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Payload {
        #[prost(message, tag = "10")]
        AgentInfo(super::AgentInfo),
        #[prost(message, tag = "11")]
        Metrics(super::MetricsSnapshot),
        #[prost(message, tag = "12")]
        ProcessList(super::ProcessList),
        #[prost(message, tag = "13")]
        ServiceMetrics(super::ServiceMetricsList),
    }
}
/// Process information - top N processes by CPU/memory
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ProcessInfo {
    #[prost(uint32, tag = "1")]
    pub pid: u32,
    /// Process name (comm)
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    /// R=running, S=sleeping, D=disk sleep, Z=zombie, etc.
    #[prost(string, tag = "3")]
    pub state: ::prost::alloc::string::String,
    /// Parent PID
    #[prost(uint32, tag = "4")]
    pub ppid: u32,
    /// CPU usage percentage
    #[prost(double, tag = "5")]
    pub cpu_percent: f64,
    /// Resident Set Size in KiB
    #[prost(uint64, tag = "6")]
    pub memory_rss_kib: u64,
    /// Virtual memory size in KiB
    #[prost(uint64, tag = "7")]
    pub memory_vsz_kib: u64,
    /// Number of threads
    #[prost(uint64, tag = "8")]
    pub threads: u64,
    /// Username (or UID if unavailable)
    #[prost(string, tag = "9")]
    pub user: ::prost::alloc::string::String,
    /// Full command line
    #[prost(string, tag = "10")]
    pub cmdline: ::prost::alloc::string::String,
    /// Process start time (jiffies since boot)
    #[prost(uint64, tag = "11")]
    pub start_time: u64,
}
/// List of processes - sent periodically (less frequently than metrics)
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ProcessList {
    #[prost(message, optional, tag = "1")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(string, tag = "2")]
    pub agent_id: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "3")]
    pub processes: ::prost::alloc::vec::Vec<ProcessInfo>,
}
/// Agent status for Last Will and Testament (LWT)
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AgentStatus {
    #[prost(string, tag = "1")]
    pub agent_id: ::prost::alloc::string::String,
    #[prost(bool, tag = "2")]
    pub online: bool,
    #[prost(message, optional, tag = "3")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
}
/// Command sent from server to agent
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Command {
    /// UUID for tracking
    #[prost(string, tag = "1")]
    pub command_id: ::prost::alloc::string::String,
    #[prost(enumeration = "CommandType", tag = "2")]
    pub command_type: i32,
    #[prost(message, optional, tag = "3")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
    /// Optional parameters depending on command type
    ///
    /// For SET_GROUP command
    #[prost(string, tag = "10")]
    pub set_group_value: ::prost::alloc::string::String,
    /// For UPDATE command (binary download URL)
    #[prost(string, tag = "11")]
    pub update_url: ::prost::alloc::string::String,
    /// SHA256 checksum for UPDATE
    #[prost(string, tag = "12")]
    pub update_checksum: ::prost::alloc::string::String,
    /// Config management parameters (for SET_CONFIG command)
    ///
    /// Configuration key (e.g., "interval_secs")
    #[prost(string, tag = "20")]
    pub config_key: ::prost::alloc::string::String,
    /// New value as string
    #[prost(string, tag = "21")]
    pub config_value: ::prost::alloc::string::String,
}
/// Response from agent to server
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CommandResponse {
    /// Matches Command.command_id
    #[prost(string, tag = "1")]
    pub command_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub agent_id: ::prost::alloc::string::String,
    #[prost(bool, tag = "3")]
    pub success: bool,
    /// Human-readable status/error message
    #[prost(string, tag = "4")]
    pub message: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "5")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
    /// Optional payload for responses that return data
    ///
    /// For GET_CONFIG response
    #[prost(message, optional, tag = "10")]
    pub config: ::core::option::Option<AgentConfig>,
    /// For GET_SWAP_PROCESSES response
    #[prost(message, optional, tag = "11")]
    pub swap_processes: ::core::option::Option<SwapProcessList>,
    /// For GET_CONFIG_SCHEMA response
    #[prost(message, optional, tag = "12")]
    pub config_schema: ::core::option::Option<ConfigSchema>,
    /// For SYNC_CONFIG response (list of added params)
    #[prost(string, optional, tag = "13")]
    pub sync_report: ::core::option::Option<::prost::alloc::string::String>,
}
/// Process using swap memory
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SwapProcessInfo {
    #[prost(uint32, tag = "1")]
    pub pid: u32,
    /// Process name (comm)
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    /// Swap usage in KiB
    #[prost(uint64, tag = "3")]
    pub swap_kib: u64,
    /// Full command line (if available)
    #[prost(string, tag = "4")]
    pub cmdline: ::prost::alloc::string::String,
    /// Username (if available)
    #[prost(string, tag = "5")]
    pub user: ::prost::alloc::string::String,
}
/// List of processes using swap
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SwapProcessList {
    #[prost(message, optional, tag = "1")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(message, repeated, tag = "2")]
    pub processes: ::prost::alloc::vec::Vec<SwapProcessInfo>,
    /// Total swap used by listed processes
    #[prost(uint64, tag = "3")]
    pub total_swap_kib: u64,
}
/// Agent configuration snapshot (for GET_CONFIG command response)
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AgentConfig {
    /// Collection settings
    #[prost(uint64, tag = "1")]
    pub interval_secs: u64,
    #[prost(uint64, tag = "2")]
    pub process_list_interval_secs: u64,
    #[prost(uint32, tag = "3")]
    pub process_top_n: u32,
    /// Network settings
    #[prost(string, tag = "10")]
    pub listen_addr: ::prost::alloc::string::String,
    #[prost(string, tag = "11")]
    pub mqtt_broker_addr: ::prost::alloc::string::String,
    #[prost(string, tag = "12")]
    pub mqtt_topic_prefix: ::prost::alloc::string::String,
    #[prost(bool, tag = "13")]
    pub mqtt_enabled: bool,
    /// MQTT Bootstrap settings
    #[prost(string, tag = "14")]
    pub mqtt_bootstrap_url: ::prost::alloc::string::String,
    #[prost(uint64, tag = "15")]
    pub mqtt_bootstrap_timeout_secs: u64,
    /// Storage settings
    #[prost(string, tag = "20")]
    pub db_file_name: ::prost::alloc::string::String,
    #[prost(bool, tag = "21")]
    pub db_save: bool,
    #[prost(uint64, tag = "22")]
    pub db_history_days: u64,
    /// Agent identity
    #[prost(string, tag = "30")]
    pub agent_group: ::prost::alloc::string::String,
    #[prost(string, tag = "31")]
    pub exclude_interfaces: ::prost::alloc::string::String,
    /// Runtime info
    ///
    /// Path to settings.toml
    #[prost(string, tag = "40")]
    pub config_path: ::prost::alloc::string::String,
    /// Resolved data directory
    #[prost(string, tag = "41")]
    pub data_directory: ::prost::alloc::string::String,
    /// Plugin settings
    #[prost(uint64, tag = "50")]
    pub plugin_interval_secs: u64,
    #[prost(bool, tag = "51")]
    pub plugins_collect_process_details: bool,
    #[prost(bool, tag = "52")]
    pub plugins_nginx_enabled: bool,
    #[prost(string, tag = "53")]
    pub plugins_nginx_service_name: ::prost::alloc::string::String,
    #[prost(bool, tag = "54")]
    pub plugins_tomcat_enabled: bool,
    #[prost(string, tag = "55")]
    pub plugins_tomcat_service_name: ::prost::alloc::string::String,
    #[prost(bool, tag = "56")]
    pub plugins_self_monitor_enabled: bool,
    #[prost(bool, tag = "57")]
    pub plugins_self_monitor_collect_open_fds: bool,
    #[prost(bool, tag = "58")]
    pub plugins_self_monitor_collect_io_stats: bool,
}
/// Individual process info within a service
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ServiceProcessInfo {
    #[prost(uint32, tag = "1")]
    pub pid: u32,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(double, tag = "3")]
    pub cpu_percent: f64,
    #[prost(uint64, tag = "4")]
    pub memory_bytes: u64,
    #[prost(uint64, tag = "5")]
    pub threads: u64,
}
/// Metrics for a single monitored service (nginx, tomcat, etc.)
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ServiceMetrics {
    /// e.g., "nginx", "tomcat", "otterwatch"
    #[prost(string, tag = "1")]
    pub service_name: ::prost::alloc::string::String,
    /// Plugin that collected this data
    #[prost(string, tag = "2")]
    pub plugin_type: ::prost::alloc::string::String,
    #[prost(bool, tag = "3")]
    pub is_running: bool,
    /// CPU metrics (from cgroup or aggregated from processes)
    ///
    /// Total CPU time in microseconds
    #[prost(uint64, tag = "10")]
    pub cpu_usage_usec: u64,
    /// CPU usage percentage (delta-based)
    #[prost(double, tag = "11")]
    pub cpu_percent: f64,
    /// User-space CPU time
    #[prost(uint64, tag = "12")]
    pub cpu_user_usec: u64,
    /// Kernel-space CPU time
    #[prost(uint64, tag = "13")]
    pub cpu_system_usec: u64,
    /// Memory metrics
    ///
    /// Current memory usage
    #[prost(uint64, tag = "20")]
    pub memory_current_bytes: u64,
    /// Swap usage
    #[prost(uint64, tag = "21")]
    pub memory_swap_bytes: u64,
    /// Anonymous memory (heap, stack)
    #[prost(uint64, tag = "22")]
    pub memory_anon_bytes: u64,
    /// File-backed memory (cache)
    #[prost(uint64, tag = "23")]
    pub memory_file_bytes: u64,
    /// Disk I/O metrics
    ///
    /// Bytes read from disk
    #[prost(uint64, tag = "30")]
    pub disk_read_bytes: u64,
    /// Bytes written to disk
    #[prost(uint64, tag = "31")]
    pub disk_write_bytes: u64,
    /// Read operations count
    #[prost(uint64, tag = "32")]
    pub disk_read_ops: u64,
    /// Write operations count
    #[prost(uint64, tag = "33")]
    pub disk_write_ops: u64,
    /// Network I/O metrics (if available)
    ///
    /// Bytes received
    #[prost(uint64, tag = "40")]
    pub net_rx_bytes: u64,
    /// Bytes transmitted
    #[prost(uint64, tag = "41")]
    pub net_tx_bytes: u64,
    /// Process/thread counts
    ///
    /// Number of processes in service
    #[prost(uint32, tag = "50")]
    pub process_count: u32,
    /// Total threads across all processes
    #[prost(uint64, tag = "51")]
    pub thread_count: u64,
    /// Data source info
    ///
    /// 1 or 2 if using cgroup
    #[prost(uint32, optional, tag = "60")]
    pub cgroup_version: ::core::option::Option<u32>,
    /// 0=unknown, 1=cgroupv2, 2=cgroupv1, 3=procfs
    #[prost(uint32, tag = "61")]
    pub data_source: u32,
    /// Per-process details (optional, for detailed view)
    #[prost(message, repeated, tag = "70")]
    pub processes: ::prost::alloc::vec::Vec<ServiceProcessInfo>,
}
/// List of service metrics - sent periodically by plugin system
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ServiceMetricsList {
    #[prost(message, optional, tag = "1")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(string, tag = "2")]
    pub agent_id: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "3")]
    pub services: ::prost::alloc::vec::Vec<ServiceMetrics>,
}
/// Single configuration parameter with metadata
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ConfigParameter {
    /// Parameter key (e.g., "interval_secs", "plugins.nginx.enabled")
    #[prost(string, tag = "1")]
    pub key: ::prost::alloc::string::String,
    /// Current value as string
    #[prost(string, tag = "2")]
    pub value: ::prost::alloc::string::String,
    /// "int", "bool", "string", "float"
    #[prost(string, tag = "3")]
    pub param_type: ::prost::alloc::string::String,
    /// Human-readable description
    #[prost(string, tag = "4")]
    pub description: ::prost::alloc::string::String,
    /// Default value
    #[prost(string, optional, tag = "5")]
    pub default_value: ::core::option::Option<::prost::alloc::string::String>,
    /// Minimum value (for numeric types)
    #[prost(string, optional, tag = "6")]
    pub min_value: ::core::option::Option<::prost::alloc::string::String>,
    /// Maximum value (for numeric types)
    #[prost(string, optional, tag = "7")]
    pub max_value: ::core::option::Option<::prost::alloc::string::String>,
    /// True if parameter was added in recent version
    #[prost(bool, tag = "8")]
    pub is_new: bool,
    /// Version when parameter was added
    #[prost(string, tag = "9")]
    pub added_in_version: ::prost::alloc::string::String,
}
/// Configuration schema - response to get-config-schema command
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ConfigSchema {
    #[prost(message, repeated, tag = "1")]
    pub parameters: ::prost::alloc::vec::Vec<ConfigParameter>,
    /// Current agent version
    #[prost(string, tag = "2")]
    pub agent_version: ::prost::alloc::string::String,
    /// Schema version
    #[prost(string, tag = "3")]
    pub config_version: ::prost::alloc::string::String,
}
/// AI analysis request (Dashboard -> Server -> AI Agent)
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AiRequest {
    /// UUID for tracking
    #[prost(string, tag = "1")]
    pub request_id: ::prost::alloc::string::String,
    /// Authentication
    #[prost(string, tag = "2")]
    pub api_key: ::prost::alloc::string::String,
    #[prost(enumeration = "AiToolType", tag = "3")]
    pub tool_type: i32,
    #[prost(message, optional, tag = "4")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
    /// Optional parameters
    ///
    /// For single-agent analysis
    #[prost(string, optional, tag = "10")]
    pub agent_id: ::core::option::Option<::prost::alloc::string::String>,
    /// For multi-agent analysis
    #[prost(string, repeated, tag = "11")]
    pub agent_ids: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Filter by group
    #[prost(string, optional, tag = "12")]
    pub agent_group: ::core::option::Option<::prost::alloc::string::String>,
    /// Analysis window (default 60)
    #[prost(uint32, optional, tag = "13")]
    pub time_window_minutes: ::core::option::Option<u32>,
    /// Custom user question
    #[prost(string, optional, tag = "14")]
    pub user_question: ::core::option::Option<::prost::alloc::string::String>,
    /// Tool-specific parameters (as JSON)
    #[prost(string, optional, tag = "20")]
    pub params_json: ::core::option::Option<::prost::alloc::string::String>,
}
/// AI analysis response (AI Agent -> Server -> Dashboard)
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AiResponse {
    /// Matches AiRequest.request_id
    #[prost(string, tag = "1")]
    pub request_id: ::prost::alloc::string::String,
    #[prost(bool, tag = "2")]
    pub success: bool,
    #[prost(string, optional, tag = "3")]
    pub error_message: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(message, optional, tag = "4")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
    /// Analysis results
    ///
    /// Markdown-formatted analysis
    #[prost(string, optional, tag = "10")]
    pub analysis_text: ::core::option::Option<::prost::alloc::string::String>,
    /// Structured insights
    #[prost(message, repeated, tag = "11")]
    pub insights: ::prost::alloc::vec::Vec<AiInsight>,
    /// Action recommendations
    #[prost(message, repeated, tag = "12")]
    pub recommendations: ::prost::alloc::vec::Vec<AiRecommendation>,
    /// Metadata
    ///
    /// LLM model name
    #[prost(string, tag = "20")]
    pub model_used: ::prost::alloc::string::String,
    /// Token consumption (if available)
    #[prost(uint32, tag = "21")]
    pub tokens_used: u32,
    /// Request processing time
    #[prost(uint32, tag = "22")]
    pub processing_time_ms: u32,
}
/// Structured insight from AI analysis
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AiInsight {
    /// "performance", "anomaly", "trend", "alert"
    #[prost(string, tag = "1")]
    pub category: ::prost::alloc::string::String,
    /// "info", "warning", "critical"
    #[prost(string, tag = "2")]
    pub severity: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub title: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub description: ::prost::alloc::string::String,
    /// Agent IDs affected
    #[prost(string, repeated, tag = "5")]
    pub affected_agents: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// "cpu", "memory", "disk", "network"
    #[prost(string, optional, tag = "6")]
    pub metric_type: ::core::option::Option<::prost::alloc::string::String>,
    /// 0.0 - 1.0
    #[prost(double, tag = "7")]
    pub confidence: f64,
}
/// AI-generated recommendation
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AiRecommendation {
    #[prost(string, tag = "1")]
    pub title: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub description: ::prost::alloc::string::String,
    /// "scale", "restart", "configure", "investigate"
    #[prost(string, tag = "3")]
    pub action_type: ::prost::alloc::string::String,
    /// "immediate", "soon", "when_possible"
    #[prost(string, tag = "4")]
    pub urgency: ::prost::alloc::string::String,
    /// Agent IDs for the action
    #[prost(string, repeated, tag = "5")]
    pub target_agents: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Suggested command if applicable
    #[prost(string, optional, tag = "6")]
    pub command_suggestion: ::core::option::Option<::prost::alloc::string::String>,
}
/// AI Agent status (published periodically)
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AiAgentStatus {
    #[prost(bool, tag = "1")]
    pub online: bool,
    #[prost(string, tag = "2")]
    pub agent_version: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub model_name: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub ollama_url: ::prost::alloc::string::String,
    #[prost(bool, tag = "5")]
    pub model_loaded: bool,
    #[prost(uint64, tag = "6")]
    pub requests_processed: u64,
    #[prost(uint32, tag = "7")]
    pub average_latency_ms: u32,
    #[prost(string, repeated, tag = "8")]
    pub available_tools: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(message, optional, tag = "9")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
}
/// Command types
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum CommandType {
    Unspecified = 0,
    /// Reload settings.toml
    ReloadConfig = 1,
    /// Restart agent process
    Restart = 2,
    /// Change agent group
    SetGroup = 3,
    /// Download and install update
    Update = 4,
    /// Health check
    Ping = 5,
    /// Request agent configuration
    GetConfig = 6,
    /// Get processes using swap
    GetSwapProcesses = 7,
    /// Set single config parameter
    SetConfig = 8,
    /// Sync config with schema (add missing params)
    SyncConfig = 9,
    /// Get full config schema with metadata
    GetConfigSchema = 10,
    /// Reconnect to MQTT broker (re-run bootstrap)
    Reconnect = 11,
}
impl CommandType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "COMMAND_TYPE_UNSPECIFIED",
            Self::ReloadConfig => "COMMAND_TYPE_RELOAD_CONFIG",
            Self::Restart => "COMMAND_TYPE_RESTART",
            Self::SetGroup => "COMMAND_TYPE_SET_GROUP",
            Self::Update => "COMMAND_TYPE_UPDATE",
            Self::Ping => "COMMAND_TYPE_PING",
            Self::GetConfig => "COMMAND_TYPE_GET_CONFIG",
            Self::GetSwapProcesses => "COMMAND_TYPE_GET_SWAP_PROCESSES",
            Self::SetConfig => "COMMAND_TYPE_SET_CONFIG",
            Self::SyncConfig => "COMMAND_TYPE_SYNC_CONFIG",
            Self::GetConfigSchema => "COMMAND_TYPE_GET_CONFIG_SCHEMA",
            Self::Reconnect => "COMMAND_TYPE_RECONNECT",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "COMMAND_TYPE_UNSPECIFIED" => Some(Self::Unspecified),
            "COMMAND_TYPE_RELOAD_CONFIG" => Some(Self::ReloadConfig),
            "COMMAND_TYPE_RESTART" => Some(Self::Restart),
            "COMMAND_TYPE_SET_GROUP" => Some(Self::SetGroup),
            "COMMAND_TYPE_UPDATE" => Some(Self::Update),
            "COMMAND_TYPE_PING" => Some(Self::Ping),
            "COMMAND_TYPE_GET_CONFIG" => Some(Self::GetConfig),
            "COMMAND_TYPE_GET_SWAP_PROCESSES" => Some(Self::GetSwapProcesses),
            "COMMAND_TYPE_SET_CONFIG" => Some(Self::SetConfig),
            "COMMAND_TYPE_SYNC_CONFIG" => Some(Self::SyncConfig),
            "COMMAND_TYPE_GET_CONFIG_SCHEMA" => Some(Self::GetConfigSchema),
            "COMMAND_TYPE_RECONNECT" => Some(Self::Reconnect),
            _ => None,
        }
    }
}
/// AI tool types for analysis requests
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum AiToolType {
    Unspecified = 0,
    /// Fleet-wide analysis
    AnalyzeFleet = 1,
    /// Single agent deep analysis
    ExplainAgent = 2,
    /// Predictive issue detection
    PredictIssues = 3,
    /// Cross-agent event correlation
    CorrelateEvents = 4,
    /// Action recommendations
    SuggestActions = 5,
    /// Period summary report
    SummarizePeriod = 6,
}
impl AiToolType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "AI_TOOL_TYPE_UNSPECIFIED",
            Self::AnalyzeFleet => "AI_TOOL_TYPE_ANALYZE_FLEET",
            Self::ExplainAgent => "AI_TOOL_TYPE_EXPLAIN_AGENT",
            Self::PredictIssues => "AI_TOOL_TYPE_PREDICT_ISSUES",
            Self::CorrelateEvents => "AI_TOOL_TYPE_CORRELATE_EVENTS",
            Self::SuggestActions => "AI_TOOL_TYPE_SUGGEST_ACTIONS",
            Self::SummarizePeriod => "AI_TOOL_TYPE_SUMMARIZE_PERIOD",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "AI_TOOL_TYPE_UNSPECIFIED" => Some(Self::Unspecified),
            "AI_TOOL_TYPE_ANALYZE_FLEET" => Some(Self::AnalyzeFleet),
            "AI_TOOL_TYPE_EXPLAIN_AGENT" => Some(Self::ExplainAgent),
            "AI_TOOL_TYPE_PREDICT_ISSUES" => Some(Self::PredictIssues),
            "AI_TOOL_TYPE_CORRELATE_EVENTS" => Some(Self::CorrelateEvents),
            "AI_TOOL_TYPE_SUGGEST_ACTIONS" => Some(Self::SuggestActions),
            "AI_TOOL_TYPE_SUMMARIZE_PERIOD" => Some(Self::SummarizePeriod),
            _ => None,
        }
    }
}
